/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_edd;

import java.io.File;
import javax.swing.JFileChooser;

/**
 * Ventana principal del Sistema de Impresiones.
 * Esta clase gestiona la interacción del usuario, visualiza la cola de impresión
 * (MinHeap) y los usuarios registrados, además de coordinar el tiempo del sistema.
 * @author karlg
 */
public class Interfaz extends javax.swing.JFrame {
    private SistemaImpresion sistema;    /** Lógica principal del sistema de impresión */
    private Reloj reloj;    /** Hilo o controlador encargado de la simulación del tiempo */

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    /**
     * Constructor de la Interfaz.
     * Inicializa los componentes visuales, el reloj y el sistema.
     * Configura el estado inicial de los botones y la ubicación de la ventana.
     */
    public Interfaz() {
        super("Sistema de Impresiones");
        initComponents();
        this.reloj = new Reloj(TiempoLabel, SegundosLabel);
        this.sistema = new SistemaImpresion(reloj);
        reloj.iniciar(); //Comienza el conteo de tiempo del sistema
        Activar(false); //Desactiva funciones hasta que se carguen usuarios
        ListaDeImpresos.setText("Ingresa un documento csv con el siquiente formato para iniciar: (Usuario, prioridad)");
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnPrintDoc = new javax.swing.JButton();
        BtnCrearDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColaTxt = new javax.swing.JTextArea();
        BtnAddUsuario = new javax.swing.JButton();
        BtnEliminarUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        UsuariosTxt = new javax.swing.JTextArea();
        BtnEliminarDoc = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();
        BtnCambiarVista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SegundosLabel = new javax.swing.JLabel();
        TiempoLabel = new javax.swing.JLabel();
        negro = new javax.swing.JLabel();
        ListaDeImpresos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnPrintDoc.setBackground(new java.awt.Color(51, 51, 51));
        BtnPrintDoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPrintDoc.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrintDoc.setText("Imprimir Documento");
        BtnPrintDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintDocActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPrintDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 10, 170, 40));

        BtnCrearDoc.setBackground(new java.awt.Color(51, 51, 51));
        BtnCrearDoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCrearDoc.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrearDoc.setText("Crear Documento");
        BtnCrearDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearDocActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCrearDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 170, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cola de Impresión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        ColaTxt.setBackground(new java.awt.Color(255, 255, 255));
        ColaTxt.setColumns(20);
        ColaTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColaTxt.setForeground(new java.awt.Color(0, 0, 0));
        ColaTxt.setRows(5);
        ColaTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ColaTxt.setEnabled(false);
        jScrollPane1.setViewportView(ColaTxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 760, 170));

        BtnAddUsuario.setBackground(new java.awt.Color(51, 51, 51));
        BtnAddUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAddUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddUsuario.setText("Añadir Usuario");
        BtnAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAddUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 150, 50));

        BtnEliminarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        BtnEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarUsuario.setText("Eliminar Usuario");
        BtnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 150, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuarios registrados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        UsuariosTxt.setBackground(new java.awt.Color(255, 255, 255));
        UsuariosTxt.setColumns(20);
        UsuariosTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsuariosTxt.setForeground(new java.awt.Color(0, 0, 0));
        UsuariosTxt.setRows(5);
        UsuariosTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        UsuariosTxt.setEnabled(false);
        jScrollPane2.setViewportView(UsuariosTxt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 590, 170));

        BtnEliminarDoc.setBackground(new java.awt.Color(51, 51, 51));
        BtnEliminarDoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEliminarDoc.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarDoc.setText("Eliminar Documento");
        BtnEliminarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarDocActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 190, 50));

        BtnImprimir.setBackground(new java.awt.Color(51, 51, 51));
        BtnImprimir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        BtnImprimir.setText("Avanzar e Imprimir");
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 190, 50));

        BtnCambiarVista.setBackground(new java.awt.Color(51, 51, 51));
        BtnCambiarVista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCambiarVista.setForeground(new java.awt.Color(255, 255, 255));
        BtnCambiarVista.setText("Cambiar Vista de la cola");
        BtnCambiarVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarVistaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCambiarVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 200, 50));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("/");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        SegundosLabel.setBackground(new java.awt.Color(0, 0, 0));
        SegundosLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SegundosLabel.setForeground(new java.awt.Color(255, 255, 255));
        SegundosLabel.setText("0S");
        SegundosLabel.setOpaque(true);
        jPanel1.add(SegundosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        TiempoLabel.setBackground(new java.awt.Color(0, 0, 0));
        TiempoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TiempoLabel.setForeground(new java.awt.Color(255, 255, 255));
        TiempoLabel.setText("Tiempo ");
        TiempoLabel.setOpaque(true);
        jPanel1.add(TiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        negro.setBackground(new java.awt.Color(0, 0, 0));
        negro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        negro.setForeground(new java.awt.Color(255, 255, 255));
        negro.setText("    .");
        negro.setOpaque(true);
        jPanel1.add(negro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 50));

        ListaDeImpresos.setEditable(false);
        ListaDeImpresos.setBackground(new java.awt.Color(255, 255, 255));
        ListaDeImpresos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ListaDeImpresos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ListaDeImpresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 760, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Controla la visibilidad de las funciones operativas del sistema.
     * @param estado true para mostrar los botones de acción, false para ocultarlos.
     */
    private void Activar (boolean estado){
        this.BtnImprimir.setVisible(estado);
        this.BtnCrearDoc.setVisible(estado);
        this.BtnEliminarUsuario.setVisible(estado);
        this.BtnEliminarDoc.setVisible(estado);
        this.BtnCambiarVista.setVisible(estado);
        this.BtnPrintDoc.setVisible(estado);
    }
    
    /**
     * Actualiza el área de texto de notificaciones con información sobre procesos actuales.
     * @param texto Mensaje informativo para el usuario.
     */
    public void setMensajeProceso(String texto) {
        this.ListaDeImpresos.setText(texto);
    }   
    
    /**
     * Recorre la lista de usuarios y construye una representación visual de 
     * cada uno junto con sus documentos asociados y sus estados.
     */
    public void ListaDeUsuariosInfo() {
        UsuariosTxt.setText(""); 
        Lista<Usuario> lista = sistema.getListaUsuarios();
    
        if (lista.esVacia()) {
            UsuariosTxt.setText("No hay usuarios registrados.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("USUARIOS Y DOCUMENTOS REGISTRADOS\n");

        for (int i = 0; i < lista.getTamaño(); i++) {
            Usuario u = lista.obtener(i);
            sb.append("USUARIO: ").append(u.getNombre()).append(" [").append(u.getTipo()).append("]\n").append("DOCUMENTOS ASOCIADOS:\n");

            
            Lista<Documentos> docs = u.getDocumentos();
            if (docs.esVacia()) {
                sb.append("(Sin documentos creados)\n");
            } else {
                for (int j = 0; j < docs.getTamaño(); j++) {
                    Documentos d = docs.obtener(j);
                    String estado = d.isEnCola() ? "[EN COLA]" : "[PENDIENTE]";
                    sb.append(d.getNombre()).append(".").append(d.getTipo())
                      .append(" - ").append(d.getTamaño()).append(" pág. ").append(estado).append("\n");
                }
            }
            sb.append("------------------------------------------\n");
        }

        UsuariosTxt.setText(sb.toString());
    }
    
    /**
     * Extrae el estado actual del MinHeap en el sistema y lo muestra 
     * en formato de tabla dentro del área de 'Cola de Impresión'.
     */
    public void ColaInfo (){
        ColaTxt.setText("");
        MinHeap heap = sistema.getColaImpresion();
        RegistroImpresion[] datos = heap.getHeap();
        int total = heap.getTamaño();

        if (total == 0) {
            ColaTxt.setText("La cola de impresión está vacía.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("ORDEN DE IMPRESIÓN:\n");
        sb.append("----------------------------------------------------------------\n");
        sb.append(String.format("%-10s | %-15s | %-10s | %-10s\n", "TIEMPO", "ARCHIVO", "TAMAÑO", "USUARIO"));
        sb.append("----------------------------------------------------------------\n");


        for (int i = 0; i < total; i++) {
            RegistroImpresion r = datos[i];
            Documentos d = r.getDocumento();

            sb.append(String.format("%-10d | %-15s | %-10d | %-15s\n", 
                      r.getEtiquetaTiempo(), 
                      d.getNombre() + "." + d.getTipo(),
                      d.getTamaño(),
                      r.getNombreUsuario()));
        }

        ColaTxt.setText(sb.toString());
    }

    /**
     * Abre la ventana para mandar a imprimir un documento, pasandole la información a la ventana.
     * @param evt 
     */
    private void BtnPrintDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintDocActionPerformed
        VentanaImprimirDoc imprimir = new VentanaImprimirDoc(sistema, this); 
        imprimir.setVisible(true);
    }//GEN-LAST:event_BtnPrintDocActionPerformed

    /**
     * Botón que al ser presionado abrirá el JFileChooser para escoger el archivo
     * csv con los usuarios para poder cargarlos al sistema.
     * @param evt 
     */
    private void BtnAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddUsuarioActionPerformed
        JFileChooser selector = new JFileChooser(); //Abre un selector de archivos para cargar usuarios.
        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File f = selector.getSelectedFile();
            Archivo gestorArchivo = new Archivo(this); 

            int cantidadCargada = gestorArchivo.CargarUsuario(f, sistema);

            if (cantidadCargada > 0) {
                Activar(true); //Empieza el sistema tras la primera carga exitosa.
                ListaDeUsuariosInfo();
            } else {

                if (ListaDeImpresos.getText().isEmpty() || ListaDeImpresos.getText().contains("Tiempo")) {
                    ListaDeImpresos.setText("Error: El archivo no tiene formato válido (Usuario, prioridad)");
                }
            }
        }
    }//GEN-LAST:event_BtnAddUsuarioActionPerformed

    /**
     * Abre la ventana de creación de documentos pasandole la información necesaria,
     * como los usuarios registrados
     * @param evt 
     */
    private void BtnCrearDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearDocActionPerformed
        VentanaCrearDoc creardoc = new VentanaCrearDoc(sistema, this); //Abre la ventana para registrar un nuevo documento a un usuario existente.
        creardoc.setVisible(true);
    }//GEN-LAST:event_BtnCrearDocActionPerformed

    /**
     * Abre la ventana de eliminación de usuario, pasandole la información necesaria
     * para funcionar, en este caso los usuarios.
     * @param evt 
     */
    private void BtnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarUsuarioActionPerformed

        VentanaElimUser eliminar = new VentanaElimUser(sistema, this);
        eliminar.setVisible(true);
        
    }//GEN-LAST:event_BtnEliminarUsuarioActionPerformed

    /**
     * Abre la ventana de eliminación de documentos, pasandole a la ventana la 
     * información necesaria para funcionar.
     * @param evt 
     */
    private void BtnEliminarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarDocActionPerformed

        VentanaElimDoc eliminardoc = new VentanaElimDoc(sistema, this);
        eliminardoc.setVisible(true);
    }//GEN-LAST:event_BtnEliminarDocActionPerformed

    /**
     * Botón que avanza en la cola de impresión, simulando que el documento
     * que está al principio de la cola se imprimió y la cola avanza
     * @param evt 
     */
    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        RegistroImpresion impreso = sistema.liberarImpresora(); //Procesa el documento con mayor prioridad (raíz del Heap)

        if (impreso != null) {
            Documentos doc = impreso.getDocumento();
            String usuario = impreso.getNombreUsuario();
            String mensaje = "Se ha impreso el documento '" + doc.getNombre() + "." + doc.getTipo() + 
                             "' del usuario '" + usuario + "' con éxito.";
            ListaDeImpresos.setText(mensaje);
            ColaInfo(); //Actualiza visualmente la cola.
            ListaDeUsuariosInfo(); //Actualiza el estado de los documentos del usuario.
            
        } else {
            ListaDeImpresos.setText("No hay documentos pendientes en la cola.");
        }
    }//GEN-LAST:event_BtnImprimirActionPerformed

    /**
     * Abre una ventana con una vista diferente de la cola de impresión
     * en forma de árbol.
     * @param evt 
     */
    private void BtnCambiarVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarVistaActionPerformed
        OtraVista vista = new OtraVista(sistema); //Abre una vista alternativa.

        vista.setVisible(true);
        vista.actuArbol();
    }//GEN-LAST:event_BtnCambiarVistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Configuración del Look and Feel (Nimbus) y lanzamiento de la interfaz */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }
    // Variables de la interfaz gestionadas por NetBeans
    // ...
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddUsuario;
    private javax.swing.JButton BtnCambiarVista;
    private javax.swing.JButton BtnCrearDoc;
    private javax.swing.JButton BtnEliminarDoc;
    private javax.swing.JButton BtnEliminarUsuario;
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JButton BtnPrintDoc;
    private javax.swing.JTextArea ColaTxt;
    private javax.swing.JTextField ListaDeImpresos;
    private javax.swing.JLabel SegundosLabel;
    private javax.swing.JLabel TiempoLabel;
    private javax.swing.JTextArea UsuariosTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel negro;
    // End of variables declaration//GEN-END:variables
}
