/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_edd;

/**
 * Ventana secundaria que proporciona una visualización gráfica en texto
 * de la estructura de datos MinHeap. Muestra la jerarquía de los documentos
 * según su etiqueta de tiempo.
 * @author karlg
 */
public class OtraVista extends javax.swing.JFrame {
    private SistemaImpresion sistema; /** Referencia al sistema para obtener los datos del heap */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OtraVista.class.getName()); /** Referencia al siguiente nodo en la lista */

    /**
     * Creates new form OtraVista
     */
    /**
     * Constructor de OtraVista.
     * @param sistema Instancia actual del sistema de impresión.
     */
    public OtraVista(SistemaImpresion sistema) {
        this.sistema = sistema;
        this.setTitle("Vista de la cola en forma de árbol");
        initComponents();
        this.setLocationRelativeTo(null);// Centra la ventana
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //Evita que al cerrar esta ventana no se cierre todo el programa.
    }

    /**
     * Punto de entrada para actualizar la representación visual del árbol.
     * Limpia el área de texto y dispara la construcción recursiva.
     */
    public void actuArbol() {
        
        VistaArbol.setText(""); 
        if (sistema.getColaImpresion().getTamaño() == 0) {
            VistaArbol.setText("La cola está vacía.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        construirArbolRecursivo(0, 0, sb);
        VistaArbol.setText(sb.toString());
    }

    /**
     * Método auxiliar recursivo que realiza un recorrido In-Order modificado.
     * Imprime primero el hijo derecho, luego el nodo actual y finalmente el izquierdo
     * para generar una vista de árbol rotada 90 grados a la izquierda.
     * @param indice Índice actual en el arreglo del heap.
     * @param nivel Profundidad actual para calcular la indentación (espaciado).
     * @param sb Acumulador de texto.
     */
    private void construirArbolRecursivo(int indice, int nivel, StringBuilder sb) {
        MinHeap heap = sistema.getColaImpresion();
        RegistroImpresion[] datos = heap.getHeap();
        int tamano = heap.getTamaño();

        if (indice < tamano) {
            construirArbolRecursivo(2 * indice + 2, nivel + 1, sb); //Recurrencia hacia el hijo derecho.
            for (int i = 0; i < nivel; i++) { //Añadir espacios según el nivel de profundidad.
                sb.append("      "); 
            }

            //Información del nodo actual: Etiqueta de tiempo y Nombre del Documento.
            sb.append("|--[T:").append(datos[indice].getEtiquetaTiempo())
              .append(" - ").append(datos[indice].getDocumento().getNombre())
              .append("]\n");
            //Recurrencia hacia el hijo izquierdo.
            construirArbolRecursivo(2 * indice + 1, nivel + 1, sb);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VistaArbol = new javax.swing.JTextArea();
        BtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VistaArbol.setEditable(false);
        VistaArbol.setColumns(20);
        VistaArbol.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        VistaArbol.setRows(5);
        jScrollPane1.setViewportView(VistaArbol);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 268));

        BtnCerrar.setText("Cerrar");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción del botón Cerrar. Libera los recursos de esta ventana.
     */
    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_BtnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JTextArea VistaArbol;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
