/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_edd;


/**
 * Ventana de selección para enviar documentos existentes a la cola de impresión.
 * Filtra los documentos para mostrar solo aquellos que no están actualmente en espera.
 * @author karlg
 */
public class VentanaImprimirDoc extends javax.swing.JFrame {
    
    private SistemaImpresion sistema;
    private Interfaz principal;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaImprimirDoc.class.getName());

    /**
     * Creates new form VentanaCrearDoc
     */
    /**
     * Constructor de la ventana.
     * @param sistema Instancia del controlador lógico.
     * @param principal Referencia a la ventana principal para actualizar las tablas.
     */
    public VentanaImprimirDoc(SistemaImpresion sistema, Interfaz principal) {
        this.sistema = sistema;
        this.principal = principal;
        this.setTitle("Mandar a imprimir un Documento");
        initComponents();
        this.setLocationRelativeTo(null);
        llenarComboDoc();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    /**
     * Recorre todos los usuarios y sus listas de documentos.
     * Solo añade al ComboBox aquellos documentos cuyo estado 'enCola' es false.
     */
    private void llenarComboDoc() {       
        Lista<Usuario> usuarios = sistema.getListaUsuarios();
        
        for (int i = 0; i < usuarios.getTamaño(); i++) {
            Usuario u = usuarios.obtener(i);
            Lista<Documentos> docs = u.getDocumentos();
            
            for (int j = 0; j < docs.getTamaño(); j++) {
                Documentos d = docs.obtener(j);
                //Evita los duplicados en la cola de impresión.
                if (!d.isEnCola()) {
                    ComboDocumentosCreados.addItem(u.getNombre() + ": " + d.getNombre());
                }
            }
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboDocumentosCreados = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnMandarImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(ComboDocumentosCreados, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 260, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Qué Documento quieres Imprimir?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 30));

        BtnMandarImprimir.setBackground(new java.awt.Color(51, 51, 51));
        BtnMandarImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnMandarImprimir.setForeground(new java.awt.Color(255, 255, 255));
        BtnMandarImprimir.setText("Imprimir");
        BtnMandarImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMandarImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMandarImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción del botón Imprimir.
     * Recupera el documento seleccionado y lo inserta en el MinHeap a través del sistema.
     */
    private void BtnMandarImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMandarImprimirActionPerformed

        String seleccion = (String) ComboDocumentosCreados.getSelectedItem();
        if (seleccion == null) return;
        
        String[] partes = seleccion.split(": "); //Separar el nombre de usuario del nombre del documento.
        String nombreUsuario = partes[0];
        String nombreDoc = partes[1];

        Usuario user = (Usuario) sistema.getTablaUsuarios().buscar(nombreUsuario); //Búsqueda O(1) del propietario.
        if (user != null) {
            Lista<Documentos> listaD = user.getDocumentos();
            //Localiza el objeto documento dentro de la lista del usuario.
            for (int i = 0; i < listaD.getTamaño(); i++) {
                Documentos d = listaD.obtener(i);

                if (d.getNombre().equals(nombreDoc)) {
                    sistema.enviarACola(d, user, d.isPrioritario()); //Envío al MinHeap con etiqueta de tiempo y prioridad.

                    String msg = d.isPrioritario() ? "Prioridad aplicada" : "Enviado a la cola.";
                    principal.setMensajeProceso(msg);

                    //Actualización de la Interfaz Principal.
                    principal.ListaDeUsuariosInfo(); 
                    principal.ColaInfo(); 
                    this.dispose();
                    break;
                }
            }
        }        
    }//GEN-LAST:event_BtnMandarImprimirActionPerformed

    /**
     * Cierra la ventana sin realizar ninguna acción.
     * @param evt 
     */
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnMandarImprimir;
    private javax.swing.JComboBox<String> ComboDocumentosCreados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
