/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_edd;

import javax.swing.JOptionPane;

/**
 * Ventana estilo formulario para la creación de nuevos documentos.
 * Permite asociar un documento a un usuario existente y definir sus propiedades básicas.
 * @author karlg
 */
public class VentanaCrearDoc extends javax.swing.JFrame {
    private SistemaImpresion sistema; /** Referencia al motor lógico del sistema */
    private Interfaz principal; /** Referencia a la ventana principal para actualizar la visualización de datos */
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCrearDoc.class.getName());

    /**
     * Creates new form VentanaCrearDoc
     */
    /**
     * Constructor de la ventana. Inicializa los componentes y carga los usuarios disponibles.
     * @param sistema Instancia actual del controlador de impresión.
     * @param principal Instancia de la interfaz principal para comunicación entre ventanas.
     */
    public VentanaCrearDoc(SistemaImpresion sistema, Interfaz principal) {
        this.sistema = sistema;
        this.principal = principal;
        this.setTitle("Crear Nuevo Documento");
        initComponents();
        this.setLocationRelativeTo(null); //Centra la ventana en pantalla
        llenarComboUsuarios();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //Evita que al cerrar esta ventana se cierre el programa completo.
    }
    
    /**
     * Recupera la lista de usuarios del sistema y los añade a una ComboBox.
     * Permite que el usuario seleccione al propietario del nuevo documento.
     */
    private void llenarComboUsuarios() {       
        Lista<Usuario> usuarios = sistema.getListaUsuarios();

        for (int i = 0; i < usuarios.getTamaño(); i++) {
            Usuario u = usuarios.obtener(i);
            if (u != null) {
                ComboUsuarios.addItem(u.getNombre()); 
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComboUsuarios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TipoDoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NombreDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TamanoDoc = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnCrear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ComboPrioridad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo de Documento (Pdf, doc, csv, etc.)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jPanel1.add(ComboUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Qué usuario creará el archivo?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));
        jPanel1.add(TipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 340, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿Es Prioritario?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));
        jPanel1.add(NombreDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 340, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tamaño del Documento (Numero de pág)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        jPanel1.add(TamanoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 340, 40));

        BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 80, 30));

        BtnCrear.setBackground(new java.awt.Color(51, 51, 51));
        BtnCrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCrear.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrear.setText("Crear");
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 80, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre del Documento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        ComboPrioridad.setForeground(new java.awt.Color(255, 255, 255));
        ComboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si" }));
        ComboPrioridad.setToolTipText("");
        jPanel1.add(ComboPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Procesa la creación del documento tras validar los campos de texto.
     * Realiza la conversión de tipos y vincula el objeto Documentos al Usuario correspondiente.
     */
    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        
        Object seleccionUsuario = ComboUsuarios.getSelectedItem();
        String nombreDoc = NombreDoc.getText().trim();
        String tamanoStr = TamanoDoc.getText().trim();
        String tipoDoc = TipoDoc.getText().trim();
     
        boolean esPrioritario = ComboPrioridad.getSelectedItem().toString().equals("Si");
        //Validaciones.
        if (seleccionUsuario == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario.");
            return;
        }

        String nombreUser = seleccionUsuario.toString();

        if (nombreDoc.isEmpty() || tamanoStr.isEmpty() || tipoDoc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }
        try {
            int tamano = Integer.parseInt(tamanoStr); //Conversión del tamaño a entero.       
            Usuario user = (Usuario) sistema.getTablaUsuarios().buscar(nombreUser); //Búsqueda O(1) del usuario en la Tabla Hash.       

            if (user != null) {            
                Documentos nuevoDoc = new Documentos(nombreDoc, tamano, tipoDoc); //Creación y configuración del objeto Documento.
                nuevoDoc.setPrioritario(esPrioritario); //Se guarda la prioridad para el futuro.
                user.agregarDocumento(nuevoDoc); //El usuario guarda el documento en su lista interna.

                String mensaje = "Documento '" + nombreDoc + "' creado para " + nombreUser;
                if (esPrioritario) mensaje += " (Marcado como Prioritario)";
                //Actualización del mensaje creado en la interfaz.
                principal.setMensajeProceso(mensaje);
                principal.ListaDeUsuariosInfo(); 

                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Error: Usuario no encontrado en el sistema.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El tamaño debe ser un número entero válido.");
        }
    }//GEN-LAST:event_BtnCrearActionPerformed

    /**
     * Cierra la ventana actual sin realizar cambios.
     */
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

   
    /**
     * @param args the command line arguments
     */   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnCrear;
    private javax.swing.JComboBox<String> ComboPrioridad;
    private javax.swing.JComboBox<String> ComboUsuarios;
    private javax.swing.JTextField NombreDoc;
    private javax.swing.JTextField TamanoDoc;
    private javax.swing.JTextField TipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
