/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_edd;


/**
 * Ventana encargada de gestionar la eliminación de documentos del sistema.
 * Implementa lógica de sincronización para eliminar archivos tanto de la lista 
 * del usuario como de la cola de prioridad (MinHeap).
 * @author karlg
 */
public class VentanaElimDoc extends javax.swing.JFrame {
    
    private SistemaImpresion sistema;
    private Interfaz principal;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaElimDoc.class.getName());

    /**
     * Creates new form VentanaCrearDoc
     */
    /**
     * Constructor de la ventana.
     * @param sistema Instancia del motor lógico.
     * @param principal Referencia a la ventana principal para refrescar vistas.
     */
    public VentanaElimDoc(SistemaImpresion sistema, Interfaz principal) {
        this.sistema = sistema;
        this.principal = principal;
        this.setTitle("Eliminar un Documento");
        initComponents();
        this.setLocationRelativeTo(null);
        llenarComboDoc();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    /**
     * Carga el ComboBox con todos los documentos existentes.
     * Incluye una lógica especial para mostrar documentos de usuarios que ya 
     * fueron eliminados pero cuyos archivos siguen en la cola de impresión.
     */
    private void llenarComboDoc() {
        //Recorre los usuarios activos y sus documentos.
        Lista<Usuario> usuarios = sistema.getListaUsuarios();
        for (int i = 0; i < usuarios.getTamaño(); i++) {
            Usuario u = usuarios.obtener(i);
            Lista<Documentos> docs = u.getDocumentos();
            for (int j = 0; j < docs.getTamaño(); j++) {
                Documentos d = docs.obtener(j);
                ComboElimDoc.addItem(u.getNombre() + ": " + d.getNombre());
            }
        }
        //Busca los documentos sin dueño en la cola.
        MinHeap heap = sistema.getColaImpresion();
        RegistroImpresion[] registros = heap.getHeap();
        for (int i = 0; i < heap.getTamaño(); i++) {
            String nombreUserEnCola = registros[i].getNombreUsuario();
            String nombreDocEnCola = registros[i].getDocumento().getNombre();
            //Si el usuario ya no existe en la tabla hash, el documento es huérfano.
            if (sistema.getTablaUsuarios().buscar(nombreUserEnCola) == null) {
                String item = nombreUserEnCola + ": " + nombreDocEnCola;

                boolean existe = false;
                for (int k = 0; k < ComboElimDoc.getItemCount(); k++) {
                    if (ComboElimDoc.getItemAt(k).equals(item)) {
                        existe = true;
                        break;
                    }
                }
                if (!existe) {
                    ComboElimDoc.addItem(item);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboElimDoc = new javax.swing.JComboBox<>();
        BtnCancelar = new javax.swing.JButton();
        BtnEliminarDoc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboElimDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboElimDocActionPerformed(evt);
            }
        });
        jPanel1.add(ComboElimDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 260, 50));

        BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 30));

        BtnEliminarDoc.setBackground(new java.awt.Color(51, 51, 51));
        BtnEliminarDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEliminarDoc.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarDoc.setText("Eliminar");
        BtnEliminarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarDocActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 80, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿Qué Documento quieres eliminar?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    /**
     * Evento principal de eliminación. Identifica al dueño y al documento, 
     * procede a borrarlo y actualiza todas las estructuras.
     */
    private void BtnEliminarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarDocActionPerformed

        String seleccion = (String) ComboElimDoc.getSelectedItem();
        if (seleccion == null){
            String mensaje = "No hay documentos para eliminar.";
            principal.setMensajeProceso(mensaje);
            this.dispose();
            return;
        }
        
        String[] partes = seleccion.split(": "); //Parseo del string "Usuario: Documento"
        String nombreUser = partes[0];
        String nombreDoc = partes[1];
        Usuario user = (Usuario) sistema.getTablaUsuarios().buscar(nombreUser);

        if (user != null) {
            Documentos docAEliminar = null;
            Lista<Documentos> listaD = user.getDocumentos();
            for (int i = 0; i < listaD.getTamaño(); i++) {
                if (listaD.obtener(i).getNombre().equals(nombreDoc)) {
                    docAEliminar = listaD.obtener(i);
                    break;
                }
            }
            if (docAEliminar != null) {
                //Si el documento estaba en la cola, aplicamos lógica de eliminación en Heap.
                if (docAEliminar.isEnCola()) {
                    eliminarDeLaCola(docAEliminar);
                }
                user.eliminarDocumento(docAEliminar);
            }
        } 
        else {
            
            MinHeap heap = sistema.getColaImpresion(); //Manejo de eliminación para documentos huérfanos en la cola.
            RegistroImpresion[] registros = heap.getHeap();
            for (int i = 0; i < heap.getTamaño(); i++) {
                Documentos d = registros[i].getDocumento();
                if (registros[i].getNombreUsuario().equals(nombreUser) && d.getNombre().equals(nombreDoc)) {
                    eliminarDeLaCola(d);
                    break;
                }
            }
        }

        String exito = "Documento eliminado con éxito.";
        principal.setMensajeProceso(exito);
        principal.ListaDeUsuariosInfo();
        principal.ColaInfo();
        this.dispose();
    }//GEN-LAST:event_BtnEliminarDocActionPerformed

    /**
     * Técnica especial para eliminar un nodo específico de un MinHeap.
     * 1. Se le asigna una prioridad máxima (valor -1) para que suba a la raíz.
     * 2. Se usa 'flotar' para moverlo a la posición 0.
     * 3. Se ejecuta eliminarMin() para remover la raíz actual.
     * @param doc Referencia del documento a remover del heap.
     */
    private void eliminarDeLaCola(Documentos doc) {
        MinHeap heap = sistema.getColaImpresion();
        RegistroImpresion[] arreglo = heap.getHeap();
        int tamaño = heap.getTamaño();

        for (int i = 0; i < tamaño; i++) {
            if (arreglo[i].getDocumento() == doc) {
                arreglo[i].setEtiquetaTiempo(-1); //Forzamos al nodo a ser el mínimo absoluto.                
                heap.flotar(i);
                heap.eliminarMin();
                break;
            }
        }
    }
    
    /**
     * Cierra la ventana de eliminación de documentos sin realizar cambios.
     * @param evt 
     */
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void ComboElimDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboElimDocActionPerformed
        
    }//GEN-LAST:event_ComboElimDocActionPerformed

    /**
     * @param args the command line arguments
     */  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminarDoc;
    private javax.swing.JComboBox<String> ComboElimDoc;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
