/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_edd;


/**
 * Ventana de diálogo para la eliminación de usuarios del sistema.
 * Gestiona la baja de usuarios y notifica a la interfaz principal para refrescar
 * las tablas de información y la vista de la cola.
 * @author karlg
 */
public class VentanaElimUser extends javax.swing.JFrame {
    /** Referencia al controlador central de lógica */
    private SistemaImpresion sistema;
    /** Referencia a la ventana principal para actualización de UI */
    private Interfaz principal;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaElimUser.class.getName());
    
    /**
     * Constructor de la ventana.
     * @param sistema Instancia del motor lógico del sistema.
     * @param principal Instancia de la interfaz de usuario principal.
     */
    /**
     * Creates new form VentanaCrearDoc
     */
    public VentanaElimUser(SistemaImpresion sistema, Interfaz principal) {
        this.sistema = sistema;
        this.principal = principal;
        this.setTitle("Eliminar Usuario");
        initComponents();
        this.setLocationRelativeTo(null); //Centra la ventana
        llenarComboUsuarios();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    /**
     * Carga el JComboBox con los nombres de todos los usuarios registrados
     * actualmente en el sistema.
     */
    private void llenarComboUsuarios() {       
        Lista<Usuario> usuarios = sistema.getListaUsuarios();
        
        for (int i = 0; i < usuarios.getTamaño(); i++) {
            Usuario u = usuarios.obtener(i);
            if (u != null) {
                ComboElimUsers.addItem(u.getNombre());
            }
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboElimUsers = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(ComboElimUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 260, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("(Esto también eliminará los documentos asociados al usuario excepto si están en cola)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 30));

        BtnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 80, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿Qué usuario quieres eliminar?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    /**
     * Ejecuta la lógica de eliminación al presionar el botón.
     * Llama al método del sistema para remover de las estructuras de datos
     * y actualiza las vistas de la cola y la lista de usuarios.
     */
    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed

        String nombreUser = (String) ComboElimUsers.getSelectedItem();

        if (nombreUser == null) {
            
            String mensaje = "No hay usuarios para eliminar";
            principal.setMensajeProceso(mensaje);
            this.dispose();
            return;
        }  
            //Eliminación en estructuras (TablaHash y Lista)
            sistema.eliminarUsuario(nombreUser);
            String mensaje = "Usuario eliminado correctamente.";
            principal.setMensajeProceso(mensaje);
            principal.ColaInfo(); //Actualiza la vista de la cola.
            principal.ListaDeUsuariosInfo(); //Actualiza la tabla de usuarios.      
            this.dispose();           
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * Cierra la ventana sin realizar ninguna acción.
     */
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JComboBox<String> ComboElimUsers;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
